<?php

require_once '/home/bmarlier/git/team_equality_maker/team-equality-maker/src/lane.class.php';

/**
 * Test class for Lane.
 * Generated by PHPUnit on 2016-06-16 at 10:52:47.
 */
class LaneTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Lane
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Lane;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Lane::getName
     * @todo Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Lane::setName
     * @todo Implement testSetName().
     */
    public function testSetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Lane::getPlayer
     * @todo Implement testGetPlayer().
     */
    public function testGetPlayer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Lane::setPlayer
     * @todo Implement testSetPlayer().
     */
    public function testSetPlayer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
